### ISSUE TITLE
distinct function not working on manipulated dataframe

### ISSUE THREAD

**Issue by GG-Delta** [pwwang/datar#129]
Hey there and thanks a lot for the game-changing datar package! It is incredible useful and just awesome! Please allow me a short question about using the distinct function: is there a way to make the distinct function work on a dataframe that was manipulated by a given operation (e.g. slice) before? 

I keep getting an error when I try to call the distinct function in this case (using your example of the documentation: https://pwwang.github.io/datar/notebooks/distinct/):

_df1 = tibble.tibble(
   x=base.sample(range(10), 100, replace=True),
   y=base.sample(range(10), 100, replace=True)
 )_

>  **The following code results in an error** ("ValueError: Value has incompatible index."):

_df1 >> dplyr.slice(base.c(1,10,12)) >>\
   dplyr.distinct(df1.x)_

>  **The following code works**:

_df2 = df1 >> dplyr.slice(base.c(1,10,12))
 df2 >> dplyr.distinct(df2.x)_

May I ask for an advice? Is there a way to make the distinct function work without the need of saving the manipulated data-frame before?
Thank you ,
Gernot

**Comment by pwwang** [comment]
This is expected.

```python
>>> df1 >> dplyr.slice(base.c(1,10,12))  # df2
         x       y
   <int64> <int64>
1        2       8
10       3       2
12       1       3
```
In your first case, you want to slice the `df2` (3 rows) on a `Series` `df1.x` (10 rows). The indices are not compatible for sure.

In your second case, you were slicing `df2` (3 rows) on `df2.x` (3 rows), and their indices are the same. That's why it worked in this case.

It would be best if you actually used the pronoun `f`, which always refers to the data frame in current environment:

```python
>>> from datar import f
>>> df1 >> dplyr.slice(base.c(1,10,12)) >> dplyr.distinct(f.x)
         x
   <int64>
1        2
10       3
12       1
```

**Comment by pwwang** [comment]
You are welcome!
Closing this for now. Feel free to open issues/discussions if you have further questions.
