### ISSUE TITLE
feature request: have simple way to create functions for use inside verbs that are unaware of groupedness

### ISSUE THREAD

**Issue by pwwang** [pwwang/datar#140]
### Discussed in https://github.com/pwwang/datar/discussions/136

<div type='discussions-op-text'>

<sup>Originally posted by **ftobin** August 26, 2022</sup>
Older versions of datar used pipda with a fairly easy to use way of creating vectorized functions:
```
@register_func(None, context=Context.EVAL)
def weighted_mean(
    x: NumericOrIter,
    w: NumericOrIter = None,
    na_rm: bool = False,
) 
```
From what I gather from the current methodology (see in the current `weighted_mean()`), there are multiple functions that needed to handle grouped/non-grouped versions of the dataframe. 

What would be great if there if there an approach that allows me to be "dplyr-ish" and just have a vectorized function that is unaware of groupedness, similar to how functions used inside of dplyr functions can work over grouped and non-grouped tibbles.</div>

**Comment by pwwang** [comment]
Proposal -

#### Registering a function

```python
@func_factory("apply_df", {"x", "w"})
def weighted_mean(df, x, w):
  """df holds aligned x and w
  x and w should be raw values passed in
  """
  return np.average(df.x, weights=df.w)
```

#### Calling the function

```python
iris >> mutate(w_mean=weighted_mean(f.Sepal_Width, f.Sepal_Length))
iris >> group_by(f.Species) >> mutate(w_mean=weighted_mean(f.Sepal_Width, f.Sepal_Length))
```

#### Implementation

When df is grouped, call `df.apply(weighted_mean)`.

**Comment by ftobin** [comment]
Can it still support other optional arguments, like `na_rm`?

FYI, `weighted_mean()` is as simple as:
```
(x*w).sum()/w.sum()
```

Maybe I'm getting a little too advanced, but couldn't the decorator inspect the argument list of the wrapped function so the vectors don't have to be specified in the call?

Also, my simple wrapper doesn't need to take a `df` and has a "normal interface" (2 arguments for weighted mean), but is hard-coded to a single pair.  Could this approach be extended to n-args easily?
```
def my_2arg_func(func):
    @singledispatch
    def _worker(
        df: DataFrame,
        **kwargs
    ) -> np.ndarray:
        return func(df["x"], df["x2"], **kwargs)
    
    @_worker.register(TibbleGrouped)
    def _(
        df: TibbleGrouped,
        **kwargs
    ) -> Series:
        return df._datar["grouped"].apply(
            lambda subdf: _worker(subdf, **kwargs)
        )

    @func_factory(None, {"x", "x2"})
    def userland(
        x: Series, x2: Series, __args_raw=None, __args_frame=None, **kwargs
    ) -> Series:
        return _worker(__args_frame, **kwargs)
    
    return userland
```

**Comment by ftobin** [comment]
I'm not sure I'm on the same page -- could you show what the user would write when they have a function to decorate?

My 2-arg solution had a bit of layering and helpers so I'd like to make sure we're talking at the same level :-)

I would think we don't want the user to have to deal with `__args_frame` and such.  The `userland()` function in my comment, part of the `my_2arg_func()` decorator doesn't require user to do anything special, simply wrap as:

```
@my_2arg_func
def my_wm(x, w):
    return (x*w).sum()/w.sum()
```

Obviously my solution is specific to two args, but it does work with kwargs fine, passing them through to the `worker()` function.

**Comment by pwwang** [comment]
Let's give a real-case example:

```python
# what the user only needs to write
@func_factory("apply_df", {"x", "w"})
def weighted_mean(x: Series, w: Series = 1, na_rm=True, __args_raw=None, __args_frame=None):
  if np.nansum(__args_frame.w) == 0:
    return np.nan
  if na_rm:
    na_mask = pd.isnull(__args_frame.x)
    x = __args_frame.x[~na_mask.values]
    w = __args_frame.w[~na_mask.values]
    if w.size == 0:
      return np.nan
    return np.average(x, weights=w)
  
  return np.average(__args_frame.x, weights=__args_frame.w)
```

Then we are able to use it in:

```python
iris >> mutate(w_mean=weighted_mean(f.Sepal_Width, f.Sepal_Length))
iris >> group_by(f.Species) >> mutate(w_mean=weighted_mean(f.Sepal_Width, f.Sepal_Length))
```

For the grouped case, `apply` will be applied internally.

**Comment by pwwang** [comment]
If you do need to handle the internal layer (i.e. the `apply` or other transformations by yourself), you should use `register_func()`.

The idea of `func_factory()` is to wrap up all the internal layers, so the user can use it as a decorator directly.

**Comment by ftobin** [comment]
I guess I'm not seeing why this code is not simpler: the user just has to do (ignoring the nan exception logic and such):

```
@my_2arg_func
def weighted_mean(x, w):
    return np.average(x, w)

iris >> group_by(f.Species) >> summarize(w_mean=weighted_mean(f.Sepal_Width, f.Sepal_Length))
```
`my_2arg_func` is defined in https://github.com/pwwang/datar/issues/140#issuecomment-1231708072

**Comment by pwwang** [comment]
Do you mean that the users have to define `my_2arg_func`?

**Comment by ftobin** [comment]
That would be provided by the package.  My implementation is specific to 2 args, but I imagine I could make it handle n-args.

**Comment by ftobin** [comment]
`my_2arg_func` is fully generic at handling 2 arguments.

**Comment by pwwang** [comment]
I get that.

But if I re-write 
```python
@func_factory("apply_df", {"x", "w"})
def weighted_mean(x: Series, w: Series = 1, na_rm=True, __args_raw=None, __args_frame=None):
  if np.nansum(__args_frame.w) == 0:
    return np.nan

  if na_rm:
    na_mask = pd.isnull(__args_frame.x)
    x = __args_frame.x[~na_mask.values]
    w = __args_frame.w[~na_mask.values]
    if w.size == 0:
      return np.nan
    return np.average(x, weights=w)
  
  return np.average(__args_frame.x, weights=__args_frame.w)
```

into a simple version like you did, it will be:

```python
@func_factory("apply_df", {"x", "w"})
def weighted_mean(x: Series, w: Series):
  # x, w can hold the broadcasted and vectorized values
  return np.average(x, weights=w)
```

This way, we don't need an extra API (other than `func_factory()` to handle single columns) and we are able to broadcast and vectorize any arguments.

**Comment by pwwang** [comment]
I think we are pretty close. The only thing is whether we should use a new API for this case, or just use `func_factory()`

**Comment by ftobin** [comment]
It doesn't matter to me if `func_factory()` implements the decorator code, but one question I have is what value is the "apply_df" string adding to what would be the "regular" definition of the weighted mean:
```
@func_factory(None, {"x", "w"})  # no "apply_df
def weighted_mean(x: Series, w: Series):
  # x, w can hold the broadcasted and vectorized values
  return np.average(x, weights=w)
```
In other words, what value does passing "apply_df" as the first argument to the decorator help with?

For clarity, if I was doing a "complete" implementation of weighted mean using the sample `my_2arg_func` (which `func_factory` could embed), and which is completely unaware of `__args_raw` and `__args_frame` and is a "regular" implementation and group-capable:
```
@my_2arg_func
def weighted_mean2(x: Series, w: Series, na_rm=True):
    if na_rm:
        not_na_mask = ~x.isna()
        x = x[not_na_mask]
        w = w[not_na_mask]
    
    if w.sum(skipna=True) == 0:
        return np.nan
    
    return np.average(x, weights=w)
```
I guess my main point is that "apply_df" doesn't seem necessary if the `my_2arg_func` logic is embedded in `func_factory`: why can't a user just specify:
```
@func_factory(None, {"x", "w"})
def weighted_mean2(x: Series, w: Series, na_rm=True):
    if na_rm:
        not_na_mask = ~x.isna()
        x = x[not_na_mask]
        w = w[not_na_mask]
    
    if w.sum(skipna=True) == 0:
        return np.nan
    
    return np.average(x, weights=w)
```

**Comment by pwwang** [comment]
`None` means there is no dispatching. It's just a bare function with x and w vectorized/broadcasted. No `apply()` applied automatically for grouped data. Just like the current implementation of `weighted_mean`. 

We could also have `agg` as the first argument, for example, then aggregation is automatically applied to the grouped data.

Other choices include `transform` and `apply`.

**Comment by ftobin** [comment]
Shouldn't dispatching simply be automatic if the data is grouped?  That's effectively what the use of `singledispatch`'s `register` does, right?  I have a hard time seeing why a user _wouldn't_ want grouped data handled automatically.

I'm not in a position to know best form for the `func_factory` arguments, but from a user perspective, I think they'd simply want to submit a vectorized function that magically works with groups if they're there (which `my_2arg_func` solves.). And no need to interact with `__args_raw/frame` in their function.

As an aside, I believe the logic of `my_2arg_func` works in both an aggregate and transform (it works both inside a `mutate` and `summarize`).  It seems to solve a superset of problems.

**Comment by pwwang** [comment]
Like I said below:

> In the earlier versions (<v0.4), the implementation was easy. That's because each group is separated and applied with the defined functions so that we don't need to consider the groupedness.

and also some other details I explained [here](https://github.com/pwwang/datar/discussions/136#discussioncomment-3486409).

It's all about performance.

Imagine the following case:

```python
from timeit import timeit
from datar.datasets import iris


gf = iris.groupby("Species")


def mysum(df):
    # handles without awareness of groupedness
    return sum(df.Sepal_Length)


def a():
    gf.apply(mysum)

def b():
    gf.Sepal_Length.sum()


ta = timeit(a, number=10000)
print(ta)  # 11.009251160998247

tb = timeit(b, number=10000)
print(tb)  # 4.163643385996693
```

**Comment by ftobin** [comment]
I understand how the performance has improved with the new approach.  My question is why doesn't the approach of `my_2arg_func`, which internally uses `func_factory(None)`, solve for both efficiency and function unawareness of groups?

**Comment by ftobin** [comment]
Ooh, am now re-reading your example code, thank you!  I think I understand the performance hit now.

**Comment by pwwang** [comment]
> Ooh, am now re-reading your example code, thank you! I think I understand the performance hit now.

There you go. 

`apply` from `pandas` makes the implementation of such unawareness of groupedness easy, but it's evil, in terms of performance.

**Comment by ftobin** [comment]
Given this, I think simply implementing the thoughts for "apply_df" into "apply" and having it trigger logic similar to `my_2arg_func` works.  The only concern I have is that it might be difficult for users to learn why their "easy" cases of simply handling grouped data requires "apply"...the naming doesn't lead the user.  Maybe I'm over-thinking :-)

The first argument to `func_factory` seems to support orthogonal concepts..is `agg` a different concept than `apply`, really?  From the user's point of view, both aggregate, but one supports "automatic" grouping.

**Comment by pwwang** [comment]
> is `agg` a different concept than `apply`, really? 

They (including `transform`) are so very different. See below:
https://pandas.pydata.org/docs/user_guide/groupby.html

But theoretically, I agree with you, that they should be the same (i.e. `R/dplyr` doesn't them). `pandas` have them because of the performance, again. `apply` can do all things, including `agg` and `transform`, but, yes, it's bad in performance.

I hope people don't have to register functions by themselves, but if they really have to, they should know the details in the above URL.

**Comment by pwwang** [comment]
`func_factory` can now register functions that are unaware of groupedness. See the new `weighted_mean` implementation:

https://github.com/pwwang/datar/blob/c0c4b6341af30572998682d18a45b92203bca4c4/datar/base/arithmetic.py#L890-L909

and also:

https://pwwang.github.io/datar/advanced/
