### ISSUE TITLE
unnest is very slow . 

### ISSUE THREAD

**Issue by antonio-yu** [pwwang/datar#156]
`unnest` takes very long time compared to the pandas methods.
For example 

```
import pandas as pd 
from datar.all import *
d ={'name': [['a','b','c','d','e','f']]*200000}
test = pd.DataFrame(d)
test >> unnest(f.name)

# it takes 1m 37.6s 


# pandas method
pd.DataFrame(np.concatenate(test.name.values))

#it takes only 2.2s
```

**Comment by pwwang** [comment]
How about `unchop`?

**Comment by antonio-yu** [comment]
@pwwang 
unchop is very fast. Only 2s taken

**Comment by pwwang** [comment]
You should use `unchop` in your case. See https://tidyr.tidyverse.org/reference/chop.html#ref-examples

In your case, you are unwrapping python lists not tibbles/dfs.

`unnest` has extra steps to parse tibbles.

**Comment by pwwang** [comment]
Close it for now.
