### ISSUE TITLE
Plugin architecture does not work with cloudpickle & loky for parallel processing

### ISSUE THREAD

**Issue by jiemakel** [pwwang/datar#162]
For example, the following code fails:
```
from datar.tibble import tibble
from joblib import Parallel, delayed, parallel_backend
with parallel_backend('loky', n_jobs=2):
    print(Parallel()(delayed(lambda a: tibble(x=a))(i) for i in [1,2])) 
```

the exception raised is `datar.core.utils.NotImplementedByCurrentBackendError: ''tibble' (backends: numpy, pandas)' (backends: numpy, pandas)`.

The problem seems to probably be some interaction between cloudpickle and simplug. If instead of a lambda or an [unpickable function](https://loky.readthedocs.io/en/stable/auto_examples/cloudpickle_wrapper.html) defined in the same file, I define the function to call in a different module, the code works. Maybe the core problem is something to do with how https://github.com/joblib/joblib/blob/master/joblib/externals/cloudpickle/cloudpickle_fast.py#L166 is interacting with simplug?

**Comment by pwwang** [comment]
Can you try this and see the output?

```python
from datar.tibble import tibble
print(tibble.registry)
```

**Comment by pwwang** [comment]
It's not the plugin architecture, it's the problem of singledispatch:

```python
from functools import singledispatch

@singledispatch
def f(x):
    return x

@f.register(int)
def _(x):
    return x + 1

@f.register(str)
def _(x):
    return x + "1"

from joblib import Parallel, delayed, parallel_backend
with parallel_backend('loky', n_jobs=2):

    print(Parallel()(
        delayed(lambda a: f(x=a))(i) for i in [1,2])
    ) 
```

raises:
```python
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/.../lib/python3.9/site-packages/joblib/externals/loky/backend/queues.py", line 153, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "/.../lib/python3.9/site-packages/joblib/externals/loky/backend/reduction.py", line 271, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/.../lib/python3.9/site-packages/joblib/externals/loky/backend/reduction.py", line 264, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/.../lib/python3.9/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'weakref' object
"""
```

`datar` uses the same architecture but without weakrefs in order to support numpy ufuncs (so that it did not raise such a TypeError).

The workaround for datar verbs/functions to work in such an environment, is you need to get the dispatched function(s) first:

```python
from datar.tibble import tibble
tibble_fun = tibble.dispatch(object, backend="pandas")

from joblib import Parallel, delayed, parallel_backend
with parallel_backend('loky', n_jobs=2):
    print(Parallel()(delayed(lambda a: tibble_fun(x=a))(i) for i in [1,2])) 
```

However, this will be complaining about some hooks not being defined, which is a code architecture thing.
The plugin hook definitions are not loaded while importing the plugin by `import` to avoid circular import. But they should be. The solution is to load the entrypoint plugins only when the APIs are called.

This will be fixed and the workaround should be working with the next version.

**Comment by pwwang** [comment]
Now with `datar` `^0.11`:

```shell
pip install -U datar[pandas]
```

The workaround works:

```python
❯ ipython                                                                            
Python 3.9.5 (default, Jun  4 2021, 12:28:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from datar.tibble import tibble 
   ...: tibble_fun = tibble.dispatch(object, backend="pandas") 
   ...: from joblib import Parallel, delayed, parallel_backend 
   ...: with parallel_backend('loky', n_jobs=2): 
   ...:     print(Parallel()(delayed(lambda a: tibble_fun(x=a))(i) for i in [1,2]))  
   ...:                                                                              
[        x
  <int64>
0       1,         x
  <int64>
0       2]
```

**Comment by pwwang** [comment]
I am considering this as resolved. But if you have further questions, feel free to reopen or open a new one.
