### ISSUE TITLE
[QST]  'Tibble' object has no attribute 'to_clipbaord'

### ISSUE THREAD

**Issue by antonio-yu** [pwwang/datar#172]
### Question about datar

I want to copy a dataframe to clipboard()

`
from datar.all import * 

(df >> mutate(test = 1) ).to_clipboard()

#'Tibble' object has no attribute 'to_clipbaord'
`

Sometimes the function 'to_clipboard()' works,but sometimes does not.

**Comment by pwwang** [comment]
Could you point out when it works and when it doesn't, and provide a reproducible and runnable code?
