### ISSUE TITLE
[BUG] ContextError: Cannot evaluate `ReferenceAttr` object without a context

### ISSUE THREAD

**Issue by sibananda-dream11** [pwwang/datar#176]
### datar version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the **latest version** of datar and its backends.

### Issue Description

Getting this error on trying to use any function(group_by,filter) from datar.
ContextError: Cannot evaluate `ReferenceAttr` object without a context

### Expected Behavior

Should have been running coreectly without any error.

### Installed Versions

<details>

0.11.2

</details>

**Comment by pwwang** [comment]
Could you provide a copy of minimal runnable code, as well as the full version information?

**Comment by sibananda-dream11** [comment]
<img width="1132" alt="Screenshot 2023-03-17 at 6 56 25 PM" src="https://user-images.githubusercontent.com/122783933/225918057-4d033fe9-dbac-4c13-8e8f-64e64060169a.png">
<img width="1132" alt="Screenshot 2023-03-17 at 6 56 44 PM" src="https://user-images.githubusercontent.com/122783933/225918135-802971c5-ae87-4c31-b4d4-90f0a3de026d.png">

**Comment by pwwang** [comment]
By the way, you also need `datar-pandas` backend to be installed:

```shell
pip install -U datar[pandas]
# or
pip install -U datar-pandas
```
