### ISSUE TITLE
bug at summarise

### ISSUE THREAD

**Issue by AInisha** [pwwang/datar#182]
### datar version checks

- [X] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the **latest version** of datar and its backends.

### Issue Description

I am unable to use summarise(CNT= n()), i donot see a separate column with CN
```
dataframe= dataframe>>group_by(f.some_col1, f.some_col2)>>summarise(CNT= n())>>ungroup() >> arrange(f.some_col2)

dataframe = (dataframe.set_index('some_col2')
                                .groupby('some_col1', sort=False)
                                .resample('MS')['CNT'].max()
                                .unstack()
                               )
```
 error throws at .resample('MS')['CNT'].max(), as there is no CNT column exist, but earlier project ran fine for months.
Please assist me as early as possible on this
tried below 2 version as these are compatible with my project, earlier it was running fine:-
```
pip install -U datar==0.9.1
pip install -U datar[pdtypes]==0.9.1

pip install -U datar==0.9.0
pip install -U datar[pdtypes]==0.9.0
```
### Expected Behavior

the column CNT existed before

### Installed Versions

<details>

Replace this line with the output of datar.get_versions()
0.9.1
</details>

**Comment by pwwang** [comment]
Please:
1. try the latest version
2. provide a runnable example

**Comment by AInisha** [comment]
for the latest version i am not bale to use the datar at all
# !pip install -U datar==0.12.2
# !pip install -U datar[pdtypes]==0.12.2

data = {'Name': ['Tom', 'nick', 'krish', 'jack', 'jack'],
        'Age': [20, 21, 19, 18, 16]}
  
# Create DataFrame
df = pd.DataFrame(data)
df>>distinct(f.Name)


below is the error
ContextError: Cannot evaluate `ReferenceAttr` object without a context.

**Comment by AInisha** [comment]
our project is built with 
pip install -U datar==0.9.1
pip install -U datar[pdtypes]==0.9.1


now i used below:-
# !pip install -U datar==0.9.1
# !pip install -U datar[pdtypes]==0.9.1

data = {'Name': ['Tom', 'nick', 'krish', 'jack', 'jack'],
        'Age': [20, 21, 19, 18, 16]}
  
# Create DataFrame
df = pd.DataFrame(data)
df>>distinct(f.Name)
df>> group_by(f.Name)>>summarise(CNT= n())>>filter(CNT>0)

**Comment by AInisha** [comment]
there is no count column displays as separate, my point is that, earlier it used to do that

**Comment by AInisha** [comment]
is there any update

**Comment by pwwang** [comment]
![image](https://github.com/pwwang/datar/assets/1188067/f84eb3ec-7b8c-4cc6-b68a-b3a6e426f8fe)

Please follow the instructions above.

Note that the error you got `NameError: name 'CNT' is not defined` is because that you need `f.CNT`.

**Comment by AInisha** [comment]
test = {'Name': ['1', '2', '2', '3', '4'],
        'Age': [20, 21, 16, 18, 16]}
  
# Create DataFrame
test1 = pd.DataFrame(test)
# test1>>distinct(f.Name)
test1>> group_by(f.Name)>>summarise(maxage= max(f.Age))>> select(f.maxage)

below is the error I get still, is it some dependencies issue?
"Columns `{'maxage'}` do not exist."



<img width="316" alt="Screenshot 2023-07-25 224556" src="https://github.com/pwwang/datar/assets/85281923/4aafeef9-14b4-43ea-a938-18df4a0d3484">

**Comment by AInisha** [comment]
still getting this errors:
I am using below, i think its library compatibility issue, Thank you for your help
python      : 3.8.10 (default, May 26 2023, 14:05:08) 
              [GCC 9.4.0]
datar       : 0.12.2
simplug     : 0.3.2
executing   : 1.2.0
pipda       : 0.12.0
datar-numpy : 0.2.0
numpy       : 1.24.4
datar-pandas: 0.3.0
pandas      : 2.0.3

**Comment by pwwang** [comment]
Can you attach the full snapshot like I did, including the code and the error.

**Comment by AInisha** [comment]
<img width="316" alt="image" src="https://github.com/pwwang/datar/assets/85281923/0e26472e-bbbf-4cb6-bede-182c0f78d9ba">

**Comment by pwwang** [comment]
I mean the full snapshot please, including the version printing, and module importing.
