### ISSUE TITLE
Can we use it with Panda 2.1?[QST] 

### ISSUE THREAD

**Issue by fkgruber** [pwwang/datar#186]
### Question about datar

Tried installing pandas backend and it removed pandas 2.1 and installed pandas 1.5.

**Comment by pwwang** [comment]
See https://github.com/pwwang/datar/projects/9#card-90413749

Support for pandas v2 is WIP.

**Comment by pwwang** [comment]
`datar` [v0.15.0](https://github.com/pwwang/datar/releases/tag/0.15.0) with `datar-pandas` [v0.5.0](https://github.com/pwwang/datar-pandas/releases/tag/0.5.0) now supports pandas v2.

Now that you still have to use numpy as your backend.
