### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by VitoFanelli** [pwwang/datar#198]
### Question about datar

Hello,

why I get two warnings when I run this code?

from datar.data import iris
from datar import f
from datar.dplyr import group_by, summarise

iris >> group_by(f.Species) >> summarise(f.Sepal_Length.mean())

C:\Users\vito\AppData\Local\Programs\Python\PYTHON~1\Lib\site-packages\pipda\utils.py:89: PipeableCallCheckWarning: Failed to detect AST node calling `group_by`, assuming a piping call.
  warnings.warn(
C:\Users\vito\AppData\Local\Programs\Python\PYTHON~1\Lib\site-packages\pipda\utils.py:89: PipeableCallCheckWarning: Failed to detect AST node calling `summarise`, assuming a piping call.
  warnings.warn(
      Species  Sepal_Length
     <object>     <float64>
0      setosa         5.006
1  versicolor         5.936
2   virginica         6.588

Thank you.

**Comment by pwwang** [comment]
Try to avoid running with raw python REPL.

See also: https://github.com/pwwang/datar/issues/196#issuecomment-1845636387
