### ISSUE TITLE
和pandas 1.2.0不兼容，pandas1.2.5可以

### ISSUE THREAD

**Issue by antonio-yu** [pwwang/datar#20]
pandas 1.2.0版本中 没有 `pandas.io.formats.format._trim_zeros_single_float` 这个函数，只有 `pandas.io.formats.format._trim_zeros_float` ，在导入datar时候就会报错

试了下panda 1.2.5 ，不报错， 要求版本可能需要提高

**Comment by pwwang** [comment]
See README. datar requires pandas 1.2.1+

**Comment by pwwang** [comment]
Fixed at [v0.2.3](https://github.com/pwwang/datar/releases/tag/0.2.3)
