### ISSUE TITLE
 how to use %in%

### ISSUE THREAD

**Issue by fkgruber** [pwwang/datar#207]
### Question about datar

In datar how to filter on a vector of possible values. For example, in R I would do:

```R
library(tidyverse)
tst = iris %>% filter(Species %in% c("setosa", "versicolor"))
tst$Species %>% unique()
```

    [1] setosa     versicolor
    Levels: setosa versicolor virginica

If I try something like this in datar using `in` instead of `%in%` I get:

```python
from datar.all import filter_, f,pull
from datar.data import iris

tst=iris >> filter_(f.Species in ["setosa","versicolor"])
print(tst.Species.unique())


```

    ['setosa' 'versicolor' 'virginica']

Is there something similar to %in% in datar?

**Comment by pwwang** [comment]
`%in%` is nothing but just the `is.element()` function in `R`. So with `datar`, we have `is_element()`. You can find an example on this page: https://pwwang.github.io/datar/notebooks/base/
