### ISSUE TITLE
cannot import name 'argname2' from 'varname' error

### ISSUE THREAD

**Issue by rleyvasal** [pwwang/datar#30]
# Issue
When importing datar, only the two lines of code below run without error, all others give the same error message `cannot import name 'argname2' from 'varname' error`. 

`from datar import f  `
`from datar.datasets import mtcars`
`from datar.dplyr import mutate, filter, if_else`
`from datar.tibble import tibble`
`from datar.all import *`

# Expected result
import any of datar packages without errors

# System information:
Windows 10
Jupyterlab version 3.0.14

pip list shows packages installed 
datar                             0.3.1
pipda                             0.4.0

# Steps taken to resolve issue
`pip uninstall datar`
`pip uninstall pipda`

restarted kernel 
`pip install -U datar`
<img width="626" alt="datar_error" src="https://user-images.githubusercontent.com/61335136/125104412-35f49300-e092-11eb-9ba5-e468c9f9c507.PNG">

**Comment by pwwang** [comment]
Hi, thanks for reporting.

Could you run `pip install -U varname` and try again?

**Comment by rleyvasal** [comment]
> Hi, thanks for reporting.
> 
> Could you run `pip install -U varname` and try again?

It is working now. Thanks @pwwang.

**Comment by rleyvasal** [comment]
@pwwang,  What are the correct steps for updating `datar` ?
Also, can you outline the steps for updating `datar` in the main github page?

I just updated `datar` and `pipda` and ran into the same issue  `cannot import name 'argname2' from 'varname'`

# Steps taken to update `datar`
`pip uninstall datar`
`pip uninstall pipda`

restarted kernel
`pip install -U datar`

**Comment by pwwang** [comment]
`pip -U` or `pip --upgrade` is not upgrading packages eagerly.
See: https://stackoverflow.com/a/64069699/5088165
So see if this works:

```
pip -U --upgrade-strategy datar
```

Or you can upgrade pipda before datar, and it will upgrade varname:

```
pip install -U pipda
pip install -U datar
```

**Comment by pwwang** [comment]
Will add varname directly to datar's dependencies in next version so that `pip install -U datar` can get varname updated.

**Comment by pwwang** [comment]
`varname` added to dependencies so that `pip install -U datar` gets `varname` updated in the next version.

Feel free to reopen if other related issues persist.
