### ISSUE TITLE
Filter multiple objects using `in` with `filter` not working

### ISSUE THREAD

**Issue by rleyvasal** [pwwang/datar#31]
# Issue

Filter multiple objects with the `filter` not working - not in the documentation.

# Expected results

Filtering multiple objects should work with `filter` verb. 

# Steps to replicate 
`from datar.datasets import mtcars`
`mtcars = mtcars.reset_index()`
`mercedes = ["Merc 230", "Merc 240D", "Merc 280"]`
`mtcars >> filter(f.index in mercedes)`

# System info
Windows 10
Jupyterlab version 3.0.14

datar 0.3.1
pipda 0.4.0
<img width="630" alt="filter_on_list" src="https://user-images.githubusercontent.com/61335136/125140514-89cd9f00-e0c7-11eb-80d9-fb9adee1cd46.PNG">

**Comment by pwwang** [comment]
You need to use `is_element()` like R's `is.element()`, which is a long-form of `%in%`.

```python
>>> from datar.datasets import mtcars
>>> from datar.all import f, rownames_to_column, is_element, filter
[2021-07-09 15:18:29][datar][WARNING] Builtin name "filter" has been overriden by datar.
>>> 
>>> mercedes = ["Merc 230", "Merc 240D", "Merc 280"]
>>> mtcars >> rownames_to_column('index') >> filter(is_element(f.index, mercedes))
       index       mpg     cyl      disp      hp      drat        wt      qsec      vs      am    gear    carb
    <object> <float64> <int64> <float64> <int64> <float64> <float64> <float64> <int64> <int64> <int64> <int64>
0  Merc 240D      24.4       4     146.7      62      3.69      3.19      20.0       1       0       4       2
1   Merc 230      22.8       4     140.8      95      3.92      3.15      22.9       1       0       4       2
2   Merc 280      19.2       6     167.6     123      3.92      3.44      18.3       1       0       4       4
```

`in` for `numpy`/`pandas` arrays does not work as `%in%` in `R` does:
```python
>>> import numpy as np
>>> 
>>> arr = np.array([1,2,3,4])
>>> elts = np.array([1,3,5])
>>> 
>>> elts in arr
/home/pwwang/miniconda3/bin/bpython:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  #!/home/pwwang/miniconda3/bin/python
False
```

In R:
```r
r$> c(1,3,5) %in% 1:4                                                                 
[1]  TRUE  TRUE FALSE

r$> is.element(c(1,3,5), 1:4)                                                         
[1]  TRUE  TRUE FALSE
```

**Comment by pwwang** [comment]
To mimic `c` in `R`, we have `datar.base.c`, which returns a `Collection` object. We can write a `__contains__` method for it so that we can do it like this in the future:

```python
from datar.base import c
# imports...
mercedes = c("Merc 230", "Merc 240D", "Merc 280")
mtcars >> filter(f.index in mercedes)
```

`mercedes` has to be a `Collection` object though.

**Comment by rleyvasal** [comment]
I can confirm  `is_element()` works for filtering multiple objects

However, `filter` with  `in`  using a `Collection` object from `datar.base.c()`  does not work. 
<img width="530" alt="in_not_working" src="https://user-images.githubusercontent.com/61335136/125142432-943e6780-e0cc-11eb-8afe-4bdef206fe02.PNG">


<img width="552" alt="is_element_works" src="https://user-images.githubusercontent.com/61335136/125142317-4b86ae80-e0cc-11eb-86c5-aa039d59e359.PNG">

**Comment by pwwang** [comment]
It's not implemented yet... Planning for 0.3.2.

**Comment by rleyvasal** [comment]
Using `isin()` on the column name also works to filter multiple objects.

`mtcars >> filter(f.index.isin(mercedes))`

<img width="492" alt="isin_works" src="https://user-images.githubusercontent.com/61335136/125143193-c3ee6f00-e0ce-11eb-8b49-49e434d5e4b5.PNG">

**Comment by pwwang** [comment]
I realize that it is impossible to implement that with the `Collection` object using `in`. As `__contains__()` in python is forced to return a scalar bool, meaning whenever we do `x in y`, `True` or `False` is instantly returned. There is no chance for us to turn `x in y` into a pipda `Expression` object for a deferred evaluation.

That's probably also why `numpy` and `pandas` arrays cannot return a bool array for `in` statement.

**Comment by pwwang** [comment]
> Using `isin()` on the column name also works to filter multiple objects.
> 
> `mtcars >> filter(f.index.isin(mercedes))`
> 
> <img alt="isin_works" width="492" src="https://user-images.githubusercontent.com/61335136/125143193-c3ee6f00-e0ce-11eb-8b49-49e434d5e4b5.PNG">

This is a great hit!!!

Will add it to the doc, as well as issues with `in` testing in python, not only in `filter`, but also in other places with similar testing.

Thanks for reporting and testing!
