### ISSUE TITLE
`filter` slows down on large datasets

### ISSUE THREAD

**Issue by rleyvasal** [pwwang/datar#37]
# Issue

When using filter in small datasets there is minimal difference in processing time between datar's `filter` and pandas `query`; however, when working with large datasets, datar's `filter` slows dramatically 

# Steps to replicate

`df_test = pd.read_excel("https://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx", dtype={"Description": str})`
`df_test >>= mutate(country2 = f.Country, country3 = f.Country, country4 = f.Country, custid2 = f.CustomerID, custid3 =  f.CustomerID, custid4=  f.CustomerID, invoice2 =f.InvoiceDate, invoice3 =f.InvoiceDate, invoice4 =f.InvoiceDate, stock2 = f.StockCode, stock3 = f.StockCode)`
`filtered_df = df_test >> filter((f.Description =="WHITE HANGING HEART T-LIGHT HOLDER" )| (f.Description =="REGENCY CAKESTAND 3 TIER") )`

Note: I artificially created more columns to show the issue.

# Snapshot comparing small dataset vs large dataset using datar's `filter` and pandas `query`
<img width="580" alt="filter_slow" src="https://user-images.githubusercontent.com/61335136/125362650-1b394d00-e324-11eb-98a2-c2afe3d4a825.PNG">

**Comment by pwwang** [comment]
There could be cython functions called inside `DataFrame.query()`, but I need to confirm.
However, before that, we can confirm whether it is because of the optimization inside `DataFrame.query()` or somewhere else. Could you try this:

```python
conditions = (df_test.Description =="WHITE HANGING HEART T-LIGHT HOLDER" ) | (df_test.Description =="REGENCY CAKESTAN
D 3 TIER")

%%time
filter(df_test, conditions)

%%time
df_test[conditions]
```

**Comment by rleyvasal** [comment]
Here is the output
<img width="408" alt="output1" src="https://user-images.githubusercontent.com/61335136/125366456-eb417800-e32a-11eb-9cb1-9bc921e6ef09.PNG">
<img width="460" alt="output2" src="https://user-images.githubusercontent.com/61335136/125366462-eda3d200-e32a-11eb-8f5e-35742980288e.PNG">

**Comment by pwwang** [comment]
Looks like that 20x time was optimized inside `.query()`. One of the reasons might be the data in the conditions are from inside the data frame itself. 

What if you do:

```python
descr = df_test.Description.copy()
df_test.query('(@descr == "WHITE HANGING HEART T-LIGHT HOLDER") | (@descr == "REGENCY CAKESTAND 3 TIER")')
```

**Comment by pwwang** [comment]
The condition aggregation is also eating the time up. There is an extra calculation:

```python
# check condition, conditions
    condition = Array([True] * _data.shape[0])
    for cond in conditions:
        if is_scalar(cond):
            cond = Array([cond] * _data.shape[0])
        condition = condition & cond

    condition[is_null(condition)] = False
    try:
        condition = condition.values.flatten()
    except AttributeError:
        ...

    out = _data[condition]
```
that I used an initial array with all `True`s. Let's try to use the first condition passed in as the initial condition and see if it helps.

Might need a `prun` to profile which steps are eating up the time.

**Comment by pwwang** [comment]
See: https://pwwang.github.io/datar/performance/#Aggregating-results-on-single-columns

**Comment by pwwang** [comment]
Closing this as `datar.dplyr.filter()` now achieves similar performance as `DataFrame.loc[]`.
