### ISSUE TITLE
`register_verb()` for cufflinks

### ISSUE THREAD

**Issue by rleyvasal** [pwwang/datar#42]
Is there a way to `register_verb()` for `cufflinks` package and pipe data to it in order to do the following with datar?

`from datar.datasets import mtcars`
`from datar.all import *`
`import cufflinks as cf`
`mtcars.reset_index().iplot(kind='bar', x= 'index', y ='mpg')`

![cufflinks_register_verb](https://user-images.githubusercontent.com/61335136/126558495-6238fd3e-ac5c-413d-8c7b-bc598c93c7ee.PNG)

**Comment by pwwang** [comment]
Looks like it works with pandas data frame in a native way. What is the way you expected it to work with datar? something like this;
```python
mtcars.reset_index() >> iplot(...)
```
?

**Comment by rleyvasal** [comment]
yes, something like the following should give out the iplot  output

`mtcars.reset_index() >> iplot(kind='bar', x= 'index', y ='mpg')`

**Comment by pwwang** [comment]
You can try:
```python
from pipda import register_verb
from datar.datasets import mtcars
from datar.all import *
import cufflinks as cf

@register_verb
def iplot(_data, *args, **kwargs):
  return _data.iplot(*args, **kwargs)
# or
# iplot = register_verb(lambda df, *args, **kwargs: df.iplot(*args, **kwargs))

mtcars.reset_index() >> iplot(kind='bar', x= 'index', y ='mpg')
```

(not tested)

**Comment by rleyvasal** [comment]
Both options work (`@register_verb ` and `iplot = register_verb(..)` )

Thanks @pwwang
