### ISSUE TITLE
pipe operator doesn't work in plain python prompt

### ISSUE THREAD

**Issue by thegiordano** [pwwang/datar#45]
seems that the pipe operator doesn't work when using datar in virtual anaconda environments.
here's a snippet of running the example code ran in anaconda prompt:

`from datar.all import f, mutate, filter, if_else, tibble`

> [2021-08-03 19:57:12][datar][WARNING] Builtin name "filter" has been overriden by datar.

```
df = tibble(
    x=range(4),
    y=['zero', 'one', 'two', 'three']
)
```

> C:\ProgramData\Anaconda3\envs\conda_start\lib\site-packages\pipda\utils.py:159: UserWarning: Failed to fetch the node calling the function, call it with the original function.
>   warnings.warn(

`df >> mutate(z=f.x)`

> C:\ProgramData\Anaconda3\envs\conda_start\lib\site-packages\pipda\utils.py:159: UserWarning: Failed to fetch the node calling the function, call it with the original function.
>   warnings.warn(
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\ProgramData\Anaconda3\envs\conda_start\lib\site-packages\pipda\register.py", line 396, in wrapper
>     return calling_rule(generic, args, kwargs, envdata)
>   File "C:\ProgramData\Anaconda3\envs\conda_start\lib\site-packages\pipda\_calling.py", line 93, in verb_calling_rule3
>     return generic(*args, **kwargs)
>   File "C:\ProgramData\Anaconda3\envs\conda_start\lib\functools.py", line 872, in wrapper
>     raise TypeError(f'{funcname} requires at least '
> TypeError: _not_implemented requires at least 1 positional argument

`mutate(df, z=f.x)`

```
>         x        y       z
>   <int64> <object> <int64>
> 0       0     zero       0
> 1       1      one       1
> 2       2      two       2
> 3       3    three       3
```

pandas 1.2.3
python 3.8.1

ps thanks a lot for the package, hopefully the issue can be closed soon :)

**Comment by pwwang** [comment]
What's the OS? Windows? Linux?
What's the python prompt? python? ipython? bpython?
What's the version of datar? `import datar; print(datar.__version__)`

**Comment by thegiordano** [comment]
> What's the OS? Windows? Linux?
windows 10
> What's the python prompt? python? ipython? bpython?
anaconda prompt (anaconda3) - python.exe
> What's the version of datar? `import datar; print(datar.__version__)`
0.4.2

**Comment by pwwang** [comment]
`pipda`, the backend of `datar` to implement the piping syntax, relies on the source code to find the AST node to detect the environment of the function to be called (whether it's in piping syntax or regular function calling). 

However, the source code is not available when the code is running in plain python prompt, thus `datar` couldn't tell if a verb is called in piping syntax.

There are several solutions for this:

1. Use a 3-rd party prompt (`ipython`, `bpython`) to run the code
2. Run the code in as a script file (`python script.py`)
3. Use a regular way to call the verbs (`mutate(df, z=f.x)`)

**Comment by thegiordano** [comment]
I'm using PyCharm with Anaconda + plain python prompt, will try switching to ipython then;

thanks so much for your quick answers!

**Comment by pwwang** [comment]
You are welcome! Thank you for reporting!

`pipda` (`v0.4.4`) has a new mode `pipda.options.assume_all_piping = True`, which handles the case where source code is not available. With this mode, the verbs are assumed to be called using piping syntax. 

`datar` will adopt this mode in the next version.

**Comment by pwwang** [comment]
With this revision https://github.com/pwwang/datar/commit/9bd9d0253a3f313e0cf5ce0fb04b6192573bb11e, one could use the "all piping" mode:

```python
from datar.all import f, mutate, filter, if_else, tibble
from pipda import options

options.assume_all_piping = True

df = tibble(
    x=range(4),
    y=['zero', 'one', 'two', 'three']
)

df >> mutate(z=f.x)
# However, without source code available, we can't have both of the above and below work:
# mutate(df, z=f.x)
```

**Comment by thegiordano** [comment]
thanks a lot for making it all clear!

is there a way to pip install the dev branch of the module to already have the [9bd9d02](https://github.com/pwwang/datar/commit/9bd9d0253a3f313e0cf5ce0fb04b6192573bb11e) revision?

I'm new to github

**Comment by pwwang** [comment]
You can do:

```
pip install git+git://github.com/pwwang/datar.git@9bd9d0253a3f313e0cf5ce0fb04b6192573bb11e
```

But I don't recommend it. It's still in development and may need more tests.

**Comment by pwwang** [comment]
Closeing. As 0.4.3 is now able run the `assume_all_piping` mode.
See: https://github.com/pwwang/datar/issues/45#issuecomment-892269117
