### ISSUE TITLE
`mutate()` error `AttributeError: REGULAR`

### ISSUE THREAD

**Issue by rleyvasal** [pwwang/datar#47]
# Steps to reproduce
from datar.all import *
from datar.datasets import mtcars
mtcars  >> mutate(mpl = f.mpg/4) 

# Expected output
Should get a column `mpl` with every value calculated from column `mpg`/4

**Comment by pwwang** [comment]
Please upgrade `pipda` to 0.4.5: `pip install -U pipda`

**Comment by rleyvasal** [comment]
thanks @pwwang. It is working now.

I thought uninstalling and installing `datar` with `pip install -U datar`  would update `pipda` automatically. 

Is there a way to have `datar`  automatically update pipda when installing  with `pip install -U datar` ?

**Comment by pwwang** [comment]
`pip install -U datar` should get all direct dependencies updated. It's wired that yours didn't.

I double-checked the `setup.py` and `pyproject.toml`, `pipda` is included. 

May need more information to reproduce this.

**Comment by rleyvasal** [comment]
I did uninstall and install before running `mutate()`, are steps below correct? 

`pip uninstall datar`
`pip install -U datar`

**Comment by pwwang** [comment]
It's correct. And you actually only need this:

```
pip install -U datar
```

`pip` will uninstall `datar` before the upgrade.

**Comment by rleyvasal** [comment]
thanks!

**Comment by pwwang** [comment]
Closing this. If this issue persists next time when upgrading `datar`, feel free to reopen it.
Also if it persists next time, could you paste the output of `pip install -U datar`?

Thanks.
