### ISSUE TITLE
ImportError: cannot import name 'VarnameException'

### ISSUE THREAD

**Issue by rleyvasal** [pwwang/datar#50]
# Issue
I just upgraded `datar` from 0.4.3 to 0.4.4 with `pip install -U datar` and got error `ImportError: cannot import name 'VarnameException'` when importing `datar` with code `from datar.all import *`

below is the error message:
```
ImportError: cannot import name 'VarnameException' from 'varname' (C:\Anaconda3\lib\site-packages\varname\__init__.py)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-268be173473d> in <module>
----> 1 from datar.all import *
      2 from datar.datasets import mtcars
      3 mtcars  >> mutate(mpl = f.mpg/4)

C:\Anaconda3\lib\site-packages\datar\all.py in <module>
      7 from .base import *
      8 from .base import _warn as _
----> 9 from .datar import *
     10 from .dplyr import _no_warn as _
     11 from .dplyr import _builtin_names as _dplyr_builtin_names

C:\Anaconda3\lib\site-packages\datar\datar\__init__.py in <module>
      1 """Specific verbs/funcs from this package"""
      2 
----> 3 from .verbs import get, flatten, drop_index
      4 from .funcs import itemgetter

C:\Anaconda3\lib\site-packages\datar\datar\verbs.py in <module>
      9 from ..core.contexts import Context
     10 from ..core.grouped import DataFrameGroupBy
---> 11 from ..dplyr import select, slice_
     12 
     13 

C:\Anaconda3\lib\site-packages\datar\dplyr\__init__.py in <module>
      4 from .across import across, c_across, if_all, if_any
      5 from .arrange import arrange
----> 6 from .bind import bind_cols, bind_rows
      7 from .context import (
      8     cur_column,

C:\Anaconda3\lib\site-packages\datar\dplyr\bind.py in <module>
     15 from ..core.names import repair_names
     16 from ..core.grouped import DataFrameGroupBy
---> 17 from ..tibble import tibble
     18 
     19 

C:\Anaconda3\lib\site-packages\datar\tibble\__init__.py in <module>
      1 """APIs for R-tibble"""
----> 2 from .tibble import tibble, tibble_row, tribble, zibble
      3 from .verbs import (
      4     enframe,
      5     deframe,

C:\Anaconda3\lib\site-packages\datar\tibble\tibble.py in <module>
      4 
      5 from pandas import DataFrame
----> 6 from varname import argname, varname, VarnameException
      7 
      8 import pipda

ImportError: cannot import name 'VarnameException' from 'varname' (C:\Anaconda3\lib\site-packages\varname\__init__.py)
```
# Expected
Expect `datar` to work without issue after upgrading to new versions.

**Comment by pwwang** [comment]
Do you still have the log when you did `pip install -U datar`?

**Comment by rleyvasal** [comment]
No log, I closed the command window after upgrading.

**Comment by pwwang** [comment]
I added `varname` directly to `pyproject.toml` and `setup.py`, and tested locally that when I did `pip install -U datar`, `varname` got upgraded as well. 

It's wired for you to not get `varname` upgraded.

Could you try:

`pip install datar==0.4.3` and then
`pip install -U datar`

and see if it works and attach the log here?

**Comment by rleyvasal** [comment]
```
Requirement already satisfied: datar in c:\anaconda3\lib\site-packages (0.4.3)
Collecting datar
  Using cached datar-0.4.4-py3-none-any.whl (10.1 MB)
Requirement already satisfied: varname in c:\anaconda3\lib\site-packages (from datar) (0.7.1)
Requirement already satisfied: pipda in c:\anaconda3\lib\site-packages (from datar) (0.4.5)
Requirement already satisfied: diot in c:\anaconda3\lib\site-packages (from datar) (0.1.1)
Requirement already satisfied: pandas<2.0,>=1.2 in c:\anaconda3\lib\site-packages (from datar) (1.3.0)
Requirement already satisfied: python-slugify<6.0.0,>=5.0.2 in c:\anaconda3\lib\site-packages (from datar) (5.0.2)
Requirement already satisfied: executing in c:\anaconda3\lib\site-packages (from datar) (0.6.0)
Requirement already satisfied: wcwidth<0.3,>=0.2 in c:\users\rls\appdata\roaming\python\python38\site-packages (from datar) (0.2.5)
Requirement already satisfied: scipy<2.0,>=1.6 in c:\anaconda3\lib\site-packages (from datar) (1.7.0)
Requirement already satisfied: pytz>=2017.3 in c:\anaconda3\lib\site-packages (from pandas<2.0,>=1.2->datar) (2021.1)
Requirement already satisfied: numpy>=1.17.3 in c:\anaconda3\lib\site-packages (from pandas<2.0,>=1.2->datar) (1.21.0)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\rls\appdata\roaming\python\python38\site-packages (from pandas<2.0,>=1.2->datar) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas<2.0,>=1.2->datar) (1.16.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\anaconda3\lib\site-packages (from python-slugify<6.0.0,>=5.0.2->datar) (1.3)
Requirement already satisfied: inflection<1.0.0 in c:\anaconda3\lib\site-packages (from diot->datar) (0.5.1)
Requirement already satisfied: pure_eval<1.0.0 in c:\anaconda3\lib\site-packages (from pipda->datar) (0.2.1)
Requirement already satisfied: asttokens<3.0.0,>=2.0.0 in c:\anaconda3\lib\site-packages (from varname->datar) (2.0.5)
Installing collected packages: datar
  Attempting uninstall: datar
    Found existing installation: datar 0.4.3
    Uninstalling datar-0.4.3:
      Successfully uninstalled datar-0.4.3
Successfully installed datar-0.4.4
```

**Comment by pwwang** [comment]
I see the problem. 

In order to keep the latest version of `varname`, the version of `varname` specified in `pyproject.toml` is `*`
But the default upgrade strategy for `pip` is "only-if-needed", which means any version of `varname` is legal and won't be upgraded.

To solve this:

`pip install -U --upgrade-strategy eager datar`

I will try to mention this in the doc.

Thanks again for reporting.

**Comment by rleyvasal** [comment]
It didn't work, I got error message: 
`ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Anaconda3\\Lib\\site-packages\\~umpy\\.libs\\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll'
Consider using the `--user` option or check the permissions.`

However, the upgrade worked after I used  the `--user`  option as shown below,:

`pip install --user -U --upgrade-strategy eager datar`

**Comment by pwwang** [comment]
That's because that `pip` is too "eager"... It's upgrading unwanted packages. 
`--upgrade-strategy eager` is too aggressive. 

Maybe try:
`pip install -U --force-reinstall datar`

but it takes longer.

**Comment by rleyvasal** [comment]
At first I got the error to install with `--user` option and after I used `pip install -U --user --force-reinstall datar` I got the error message below (still trying to upgrade other packages):

```
Attempting uninstall: scipy
    Found existing installation: scipy 1.7.1
    Uninstalling scipy-1.7.1:
      Successfully uninstalled scipy-1.7.1
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\rls\\AppData\\Roaming\\Python\\Python38\\site-packages\\~cipy\\.libs\\libansari.R6EA3HQP5KZ6TAXU4Y4ZVTRPT7UVA53Z.gfortran-win_amd64.dll'
Check the permissions.
```

**Comment by pwwang** [comment]
`scipy` is an optional dependency of `datar`. Well, guess for you the easiest way is:

```
pip install -U varname
pip install -U datar
```

I will keep digging to see if there is a better way for this situation.

**Comment by pwwang** [comment]
@rleyvasal Here are the results:

The default upgrading strategy for pip is `only-if-needed`. When no version is specified for a package in `setup.py`, it tries to no upgrade the package. So the solution could be either:

1. on my end, to specify a specific version number to all dependencies. But that requires us to pump a new version of `datar` each time any dependency publishes a new version
2. on user's end, to upgrade the dependencies manually, use `--upgrade-strategy eager` and maybe `--user` together if necessary.

**Comment by rleyvasal** [comment]
@pwwang, I would prefer your previous solution:

```markdown
pip install -U varname
pip install -U datar
```
`--upgrade-strategy eager` with `--user` is slower and upgrades other packages that I may not want to upgrade,  e.g.  `scipy`.

Can we use `pip install` to upgrade `datar` and `varname`  and make this  option 3?

**Comment by pwwang** [comment]
Of course, just do:

```
pip install -U varname datar
```

**Comment by pwwang** [comment]
@rleyvasal  This is a great proposal. I will mention this in the doc.

> Of course, just do:
> 
> ```
> pip install -U varname datar
> ```
