### ISSUE TITLE
from datar.all import * doesn't import trimws

### ISSUE THREAD

**Issue by Mrostgaard** [pwwang/datar#58]
Hello pwwang

I tried to call: 
from datar.all import * 
and it worked fine, but when I needed trimws I had to import using
from datar.base.string import trimws

If it is a intended functionality please just close the issue

**Comment by pwwang** [comment]
Ah, it's absolutely not intentional. Good catch! Will add it in the next version.

**Comment by pwwang** [comment]
Added at [v0.5.1](https://github.com/pwwang/datar/releases/tag/0.5.1)
