### ISSUE TITLE
`datar` not working on RStudio notebooks

### ISSUE THREAD

**Issue by rleyvasal** [pwwang/datar#67]
I am trying to run code on RStudio R notebooks with `datar` but the code does not run. I would like to use R notebooks to highlight parts of the `datar` code and run separately. 

@pwwang  what is the issue with running `datar` on RStudio. 

![datar_rstudio](https://user-images.githubusercontent.com/61335136/136274110-9acf030d-7498-48ab-b086-e5e9b63a3994.PNG)

**Comment by pwwang** [comment]
This is because the source code is not available for `datar`/`pipda` to detect the piping syntax. 
See also the following for solutions:

https://pwwang.github.io/datar/caveats/blind/

**Comment by pwwang** [comment]
Here you go:
````python
```{python}
from pipda import options
from datar.all import * 
from datar.datasets import mtcars
options.assume_all_piping = True

mtcars >> mutate(carb_2 = f.carb)
```
````

**Comment by antonio-yu** [comment]
@rleyvasal @pwwang 

If in Rsutio with the latest version , it both works whether ` options.assume_all_piping = True`  goes before the datar importing or not.


![image](https://user-images.githubusercontent.com/69033563/137571894-136d8e97-3a65-47d5-8931-b52b9f2718d0.png)

**Comment by antonio-yu** [comment]
@pwwang @rleyvasal 
In the latest Rstudio (version 2021.09.0 ),it both works whether `options.assume_all_piping = True `goes before the datar importing or not.

```
{python}
from datar.all import  * 
from pipda import options,register_verb
from datar.datasets import mtcars
options.assume_all_piping = True 
mtcars >> mutate(carb_2=f.carb)
```

**Comment by pwwang** [comment]
Then I will close this for now. If you have any related questions, feel free to reopen it or open new issues.

**Comment by rleyvasal** [comment]
@pwwang, just curious, do you know why the pipes work without `pipda` configuration in VSCode's Jupyter notebooks? but in RStudio notebooks we have to enter the following:

````python

```{python}
from pipda import options
options.assume_all_piping = True
```
````

**Comment by pwwang** [comment]
@rleyvasal Just took a look at how Rstudio is running python. It actually executes python code with something like `eval()` wrapped by `reticulate`. It does not ship with the source code. So currently we need that assumption to let `datar` work. But I will keep on an eye on `reticulate`'s evolution, and see if it'll be possible in the future. And maybe submit an issue to the repo at some time point.
