### ISSUE TITLE
Any plans to add new functions like fast_mutate in siuba

### ISSUE THREAD

**Issue by antonio-yu** [pwwang/datar#68]
In big data ,it always takes long time in `mutate `after `group by `.
I found the` fast_mutate`,` fast_summarize` in siuba does short the time a lot.
So do you have any plans to add some functions like that to optimize the grouped data.

**Comment by pwwang** [comment]
Yes, the optimization will be done gradually in a long term, but it'll not be something like fast_mutate. It will be integrated with `mutate` itself. The optimization will be automatically performed when possible. You may take a look at `arrange` to see how that works:

https://github.com/pwwang/datar/blob/4e2b5db026ad35918954576badef9951928c0cb1/datar/dplyr/arrange.py#L55-L67

But I do need to take a look at some details of how those `fast_*` functions were implemented.

**Comment by antonio-yu** [comment]
Glad to hear that.
You are really doing a great job.

**Comment by pwwang** [comment]
With 0.6.0, those verbs are already their fast version. Mind giving it a try?

**Comment by pwwang** [comment]
I assume that this is addressed.
