### ISSUE TITLE
semi_join returns duplicated rows

### ISSUE THREAD

**Issue by AhmedAliStats** [pwwang/datar#71]
First of all, I would like to thank you for the amazing effort you have put into this work.

I would like to point an issue with the current implementation of the semi_join function; if a row in the left tibble corresponds to multiple rows in the right tibble, it will return duplicated rows because of the use of a left join.

Here is a minimal example.

```
import pandas as pd
from datar.all import *

df1 = pd.DataFrame({'x': [1, 2, 3, 4, 5]})
df2 = pd.DataFrame({'x': [1, 2, 2, 3]})

semi_join(df1, df2, by='x')
```

This gives the output
```
        x
  <int64>
0       1
1       2
2       2
3       3
```

Just in case that this might help, I have used the following approach for semi_join and anti_join before (don't remember if I got this from StackOverflow or not!).
```
import pandas as pd

def anti_join(left_df, right_df, on):
    return left_df.loc[~left_df.loc[:, on].apply(tuple, axis=1).isin(right_df.loc[:, on].apply(tuple, axis=1))]

def semi_join(left_df, right_df, on):
    return left_df.loc[left_df.loc[:, on].apply(tuple, axis=1).isin(right_df.loc[:, on].apply(tuple, axis=1))]

df1 = pd.DataFrame({'x': [1, 2, 3, 4, 5]})
df2 = pd.DataFrame({'x': [1, 2, 2, 3]})

semi_join(df1, df2, on=['x'])
anti_join(df1, df2, on=['x'])
```

Again, thank you very much for this work.

**Comment by antonio-yu** [comment]
@pwwang , no update for 2 months. 
Any big plans ?

**Comment by pwwang** [comment]
> @pwwang , no update for 2 months. 
> Any big plans ?

@antonio-yu Thanks for checking in. My own job was slowing me down. But I AM working on the optimization part.
