### ISSUE TITLE
Any way to stop the re package  being overwritten?

### ISSUE THREAD

**Issue by antonio-yu** [pwwang/datar#73]
re is needed to do regular expressions.
Then re has to be imported after the datar.

```
from datar.all import *
import re
```
I always import re first.Then id doesn't work after being overwritten.
Sometimes I use re in function like this :

```
def test(x,y) 
   re.sub(..)
   re.replace(..)
   return ...

```

**Comment by pwwang** [comment]
- Option 1:
    Alias the `re` package: `import re as pyre`
- Option 2:
    Import the functions individually from `datar`. For `re`, you can do `from datar.all import re_` or `from datar.all import re as re_`
- Option 3:
    Sort of derived from option 2. But you only need to import functions from `datar.base` individually. For example, you are using a lot of functions from `datar.dplyr`:
    ```python
    import re
    from datar.base import re_ # other functions from datar.base
    from datar.dplyr import *
    # your code
    ```

**Comment by pwwang** [comment]
Assuming this question is answered. Feel free to reopen if further questions arise.

**Comment by antonio-yu** [comment]
@pwwang 
有个建议不知道可不可行
我觉得re这个名称不应该被覆盖, 其他几个被覆盖的都是内置函数,用到的毕竟不算多;
 re这个是内置的基本包,使用还是蛮频繁的. 有没有办法默认不覆盖它. 

我对包不是很理解啊, 可能问的问题有些外行. 
我在.../base/__init__.py文件里, 看到re已经是被替换为re_
`from .complex import arg, as_complex, conj, im, is_complex, mod, re as re_`
为啥从 `from datar.all import *` 还是导入是re 而不是re_呢 ?
而导入具体名称的话 就是`re_`了 `from datar.all import re_`.

能不能无论是from datar.all 还是单独导入, 都是导入re_, 这样就不覆盖re包了.

**Comment by pwwang** [comment]
I sort of agree with you:

1. `re` is actually not a builtin name, it's an imported name
2. `base.complex.re()` is barely used, unlike `sum`, `min`, `max`, etc.

The best option is probably to just use `re_` for `from datar.all import *` or `from datar.base import *`

**Comment by antonio-yu** [comment]
或者是不覆盖原有的内置函数; 
重名的函数 如  sum,min,max等等 无论通过哪个方式导入, 都默认名称加个 '_';

**Comment by pwwang** [comment]
Now ([0.8.0](https://github.com/pwwang/datar/releases/tag/0.8.0)) you can use the option `import_names_conflict` to change the behavior:

```python
>>> from datar import options
>>> options(import_names_conflict="warn")
>>> from datar.all import *
[2022-04-12 00:29:21][datar][WARNING] Builtin name "min" has been masked by datar.
[2022-04-12 00:29:21][datar][WARNING] Builtin name "slice" has been masked by datar.
[2022-04-12 00:29:21][datar][WARNING] Builtin name "sum" has been masked by datar.
[2022-04-12 00:29:21][datar][WARNING] Builtin name "max" has been masked by datar.
[2022-04-12 00:29:21][datar][WARNING] Builtin name "round" has been masked by datar.
[2022-04-12 00:29:21][datar][WARNING] Builtin name "re" has been masked by datar.
[2022-04-12 00:29:21][datar][WARNING] Builtin name "abs" has been masked by datar.
[2022-04-12 00:29:21][datar][WARNING] Builtin name "any" has been masked by datar.
[2022-04-12 00:29:21][datar][WARNING] Builtin name "filter" has been masked by datar.
[2022-04-12 00:29:21][datar][WARNING] Builtin name "all" has been masked by datar.
```

```python
>>> from datar import options
>>> options(import_names_conflict="silent")
>>> from datar.all import *
>>> re
<function real at 0x7f6fcc9d84c0>
```

```python
>>> from datar import options
>>> options(import_names_conflict="underscore_suffixed")
>>> from datar.all import *
>>> re
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    re
NameError: name 're' is not defined
>>> re_
<function real at 0x7f0b7dedd790>
```

See more details at: https://pwwang.github.io/datar/import/#warn-about-python-reserved-names-to-be-masked-by-datar

If you feel like changing the options each time when you import `datar` is annoying, you can change the default options in `~/.datar.toml` or `./.datar.toml`. For example, put the following in `~/.datar.toml`:
```toml
import_names_conflict = "underscore_suffixed"
```

See more details at: https://pwwang.github.io/datar/options/#configuration-files

**Comment by antonio-yu** [comment]
Coding in pycharm,some erros  with Ipython

```
In[1]: from datar import options
In[2]: options(import_names_conflict="underscore_suffixed")
In[3]: from datar.all import *
Traceback (most recent call last):
  File "D:\programfiles\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-78-42bd90865353>", line 1, in <module>
    from datar.all import *
  File "D:\programfiles\anaconda\lib\site-packages\datar\core\import_names_conflict.py", line 47, in _getattr
    raise AttributeError
AttributeError

```

**Comment by pwwang** [comment]
I tried on ipython 7.28. Everythhing runs okay. Could you show `get_versions()`:

```python
Python 3.9.5 (default, Jun  4 2021, 12:28:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.28.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from datar import options
[2022-04-12 19:51:39][datar][WARNING] Package `pdtypes` not installed for `options(enable_pdtypes=True)`

In [2]: options(import_names_conflict="underscore_suffixed")

In [3]: from datar.all import *

In [4]: from datar import get_versions

In [5]: get_versions()
python   : 3.9.5 (default, Jun  4 2021, 12:28:51) 
           [GCC 7.5.0]
datar    : 0.8.0
numpy    : 1.22.3
pipda    : 0.5.9
executing: 0.8.3
varname  : 0.8.3
pandas   : 1.4.2
```

**Comment by antonio-yu** [comment]
python   : 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
datar    : 0.8.0
numpy    : 1.20.1
pipda    : 0.5.9
executing: 0.8.0
varname  : 0.8.1
pandas   : 1.4.1

**Comment by pwwang** [comment]
Try `pip install -U varname`.

pipda doesn't pin varname version. Will pin in next version.

**Comment by antonio-yu** [comment]
Resolved.

**Comment by antonio-yu** [comment]
It's strange tha the same erros occoured again both in pycharm and VScode. 
```
from datar import options
options(import_names_conflict="underscore_suffixed")
from datar.all import *

```

In vscode, erros:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\Users\YULIAN~1\AppData\Local\Temp/ipykernel_154492/1230869652.py in <module>
      1 from datar import options
      2 options(import_names_conflict="underscore_suffixed")
----> 3 from datar.all import *

D:\programfiles\anaconda\lib\site-packages\datar\core\import_names_conflict.py in _getattr(name)
     45             or opt_maybe_changed == "underscore_suffixed"
     46         ):
---> 47             raise AttributeError
     48 
     49         # from ... import xxx

AttributeError: 
```

In pycharm, erros:

```
Traceback (most recent call last):
  File "D:\programfiles\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-e54b43bafab0>", line 3, in <module>
    from datar.all import *
  File "D:\programfiles\anaconda\lib\site-packages\datar\core\import_names_conflict.py", line 47, in _getattr
    raise AttributeError
AttributeError
```

**Comment by antonio-yu** [comment]
python   : 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
datar    : 0.8.0
numpy    : 1.20.1
pipda    : 0.5.9
executing: 0.8.3
varname  : 0.8.3
pandas   : 1.4.1

**Comment by pwwang** [comment]
It's weird. I conda'ed the same exact environment as yours, but can't reproduce the issue:

```python
Python 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.28.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from datar import get_versions
[2022-04-14 23:51:02][datar][WARNING] Package `pdtypes` not installed for `options(enable_pdtypes=True)`

In [2]: get_versions()
python   : 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
datar    : 0.8.0
numpy    : 1.20.1
pipda    : 0.5.9
executing: 0.8.3
varname  : 0.8.3
pandas   : 1.4.1

In [3]: from datar import options

In [4]: options(import_names_conflict="underscore_suffixed")

In [5]: from datar.all import *

In [6]: re_
Out[6]: <function numpy.real(__x, *args, **kwargs)>
```

I currently don't have PyCharm but I tried with vscode jupyter:

![image](https://user-images.githubusercontent.com/1188067/163535927-ca0dee30-a7d1-485b-92f6-5a575f3494cc.png)

Could you make sure the python you used to print the versions and the one that produces the error are the same ones?

**Comment by pwwang** [comment]
What the ipython version again? The one I used is 7.28.

**Comment by antonio-yu** [comment]
Yeah, I only have one python installed, which is  
`Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] on win32`

It worked yesterday, maybe some conflicts with other packages. 
Never mind, I'll try to find it out.

**Comment by antonio-yu** [comment]
IPython 7.27.0

python   : 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
datar    : 0.8.0
numpy    : 1.20.1
pipda    : 0.5.9
executing: 0.8.3
varname  : 0.8.3
pandas   : 1.4.1

**Comment by antonio-yu** [comment]
What's most weird is,
I didn't reboot the pc ,nor pip any new packages either

**Comment by pwwang** [comment]
Switched to ipython 7.27, still couldn't reproduce.

Could you try to modify this file:

`D:\programfiles\anaconda\lib\site-packages\datar\core\import_names_conflict.py`

by changing `raise AttributeError` to `raise AttributeError(name)` on line 47, to see what will be printed?

**Comment by antonio-yu** [comment]
After the modification,now it works .

**Comment by pwwang** [comment]
Uhh... Can't find an appropriate emoji here to use :awkward: 
I can't tell why from the information we have here...

**Comment by pwwang** [comment]
When you restore the file (by changing `raise AttributeError(name)` to `raise AttributeError`), will the error reoccur?

**Comment by antonio-yu** [comment]
Nope, It still works!!! No errors!!

**Comment by antonio-yu** [comment]
I will retry  it on  my private pc after work.

**Comment by pwwang** [comment]
Alright. I guess there was some caching being triggered.

**Comment by antonio-yu** [comment]
> You can change the default behavior of datar by configuring a .toml.toml file in your home directory. For example, to always use underscore-suffixed names for conflicting names, you can add the following to your ~/.datar.toml `file:`
`import_names_conflict = "underscore_suffixed"`

Whic directory should be the home directory. 
For example, does it refer to 'D:\programfiles\anaconda\lib\site-packages\datar' in my pc?

**Comment by pwwang** [comment]
See this:

https://stackoverflow.com/a/33244431/5088165
