### ISSUE TITLE
(Optim) Conda-Forge Recipe

### ISSUE THREAD

**Issue by AhmedAliStats** [pwwang/datar#74]
Any plans to sumbit datar to Conda-Forge?

Thank you very much.

**Comment by pwwang** [comment]
Hi @AhmedAliStats, I don't plan to maintain that but I am glad if someone does it and I can offer some help if needed.

**Comment by pwwang** [comment]
The recommended way to install is to use `pip`. Closing this for now.

**Comment by pwwang** [comment]
Thank you! Appreciated!
