### ISSUE TITLE
Function to write dataframe to CSV like readr `write_csv()`

### ISSUE THREAD

**Issue by rleyvasal** [pwwang/datar#76]
Hi @pwwang,  

Happy New Year!, I hope you had a great holiday break.

I want to save the output/dataframe of a pipe into a csv file the way `write_csv()`  does in `readr dplyr` but I did not find a function in the documentation.

Is there a `write_csv()`  function in `datar`?
 
This is the way it works in R notebook

````rmarkdown
```{r}
library(tidyverse)
```

```{r}
mtcars |> group_by(mpg) |> count(cyl) |> write_csv('mpg.csv')
```

````

This is what I tried with `datar` and did not work

````markdown
from datar import *
from datar.datasets import mtcars
mtcars >> group_by(f.mpg) >> count(f.cyl) >> write_csv('mpg.csv')
````

**Comment by pwwang** [comment]
There is no such verb `write_csv()`. The result is a pandas data frame most of the time so that you can do whatever is available with a pandas data frame:

```python
from datar import *
from datar.datasets import mtcars
df = mtcars >> group_by(f.mpg) >> count(f.cyl) 
df.to_csv('mpg.csv')
```

If you want that piping syntax, you can define your own `write_csv()` verb:
```python
from pipda import register_verb
from datar import *
from datar.datasets import mtcars
@register_verb
def write_csv(df, *args, **kwargs):
  df.to_csv(*args, **kwargs)

mtcars >> group_by(f.mpg) >> count(f.cyl) >> write_csv('mpg.csv')
```

**Comment by rleyvasal** [comment]
Thanks @pwwang !
