### ISSUE TITLE
Cannot `rename()` column to name with spaces

### ISSUE THREAD

**Issue by rleyvasal** [pwwang/datar#85]
I want to change column names  to name with spaces as following; however, the code below does not work. 

is there a way to do this with `datar`?

```python
mtcars >> rename(f['miles per gallon'] = f.mpg)

```

**Comment by pwwang** [comment]
![image](https://user-images.githubusercontent.com/1188067/157514929-e440277d-01eb-4702-9402-e6353dde5a26.png)

**Comment by rleyvasal** [comment]
that works, thank you!

**Comment by rleyvasal** [comment]
Just curious,
why the column name cannot be referenced as f['miles per gallon']  ?

**Comment by pwwang** [comment]
Because it's not a valid syntax in python to use expressions as keyword arguments:
```python
func(a=1, b=2)  # valid
func(a.b = 1) # invalid
```
