### ISSUE TITLE
Operator `&` losing index

### ISSUE THREAD

**Issue by rleyvasal** [pwwang/datar#87]
when the case_when is used the output is not as expected. 

## Code to replicate

```python
mtcars >> mutate(gas_milage = case_when(
                            f.mpg >21  and f.mpg <= 22, "ok",
                            f.mpg >22, "best",
                            True, "other"

))
```

## Issue: The last line in the output does not meet the f.mpg >21  and f.mpg <= 22, "ok"  but it is still applied the "ok" label
![case_when](https://user-images.githubusercontent.com/61335136/157727641-19c720a8-a9f9-4b1c-bc97-4334bbc41a7f.PNG)

# Expected result
Only rows meeting the  f.mpg >21  and f.mpg <= 22, "ok" condition labeled "ok", all other rows not meeting any condition should be labeled "other"

**Comment by pwwang** [comment]
You might want to try 

```
f.mpg >21 & f.mpg <= 22
          ^
``` 

instead of `f.mpg >21 and f.mpg <= 22`

**Comment by rleyvasal** [comment]
that works - it was the & and parenthesis
thanks!

**Comment by pwwang** [comment]
Did you get it to work? I actually got an error instead:
`ValueError: Value has incompatible index.`

And I found that it is actually a bug for `&` to lose the index in the operator handling.

**Comment by rleyvasal** [comment]
Thanks for the update!

**Comment by pwwang** [comment]
A commit has been made to fix this. It will be included in v0.6.2

**Comment by pwwang** [comment]
There is a change since 0.6.0 that `f[f.name:f.mass]` will not include column `mass`. You either 
- specify the `stop` of the slice to the next column `f[f.name:f.hair_color]`, or 
- explictly specify the `step`: `f[f.name:f.mass:1]`

to include the `stop` (column `mass` here)

See the latest version:

https://pwwang.github.io/datar/notebooks/case_when/

**Comment by rleyvasal** [comment]
I confirm `|` is working as expected.

**Comment by rleyvasal** [comment]
just curious, what prompted the change on 0.6.0?

The following line of code makes it very clear the range of columns from `name` to `mass ` are being selected:
```python
starwars >>   select(f[f.name:f.mass])
```
However, the new way of selecting a range of columns is counterintuitive: (specify `hair_color` as the cutoff point to select all columns before that?)

```python
starwars >>   select(f[f.name:f.hair_color])
```

**Comment by pwwang** [comment]
There are a couple of reasons:

1. Current behavior is consistent with python's slice, for example:
    `f[:3]` expands to [0, 1, 2]
2. The selector is actually able to handle a mixture of column names and indices:
   `f[f.name:3]` and `f[f.name:f.hair_color]` selects the same set of columns.

**Comment by rleyvasal** [comment]
Related to this issue 

When using multiple `.between`to select a range of values, how does `case_when()` evaluate the conditions?
e.g. when using in the following code ,  mpg 21.0 is assigned "ok" label - not "better"

is it because ` f.mpg.between(16,21), "ok",`  it was evaluated first?

is there a better way of writing the code?
 
```python
mtcars >> select(f.mpg) >> mutate(case_when(
    f.mpg.between(0,16), "bad",
    f.mpg.between(16,21), "ok",
    f.mpg.between(21,24), "better",
    f.mpg>24, "best",
    True, "other"
))
```

![case_when_2](https://user-images.githubusercontent.com/61335136/157936408-00fa6387-8e02-4cca-8af5-d65167c8cc35.PNG)

The following code has boundaries clearly defined (cannot test it yet because of the `ValueError: Value has incompatible index.`)

```python
mtcars >> mutate(case_when(
    (f.mpg >= 0) & (f.mpg <= 16), "bad",
    (f.mpg > 16) & (f.mpg <= 21), "ok",
    (f.mpg > 21) & (f.mpg <= 24), "better",
    f.mpg>24, "best",
    True, "other"
))
```
